### ISSUE TITLE
 -XX:+UseCompressedOops 在64位jvm是什么

### ISSUE THREAD

**Issue by bee06** [bee06/note#2]
1. 1. -XX:+UseCompressedOops 命令行选项是64位JVM最常用的选项之一
2. 2. 虽然64位JVM允许您指定更大的Java堆大小，但是使用64位OOPS会降低性能。普通对象指针（也称为OOPS，用于表示虚拟机中的Java对象）的宽度增加了64位，而不是早期32位JVM的32位宽度。
3. 3. 由于OOPS的大小增加，可以在CPU高速缓存寄存器中存储更少的OOPS，这有效地降低了CPU高速缓存效率。 -XX：+ UseCompressedOops允许在64位JVM中使用压缩的32位OOPS，有效地补偿了64位JVM带来的性能损失，而不会影响它们提供的堆大小优势。
4. 如果-Xmx指定的最大堆大小小于32G，则应使用-XX：+ UseCompressedOops。

**Comment by BackerQ** [comment]
堆大于32g使用该参数会怎样呢，为什么不是4g呢正好寻址是2的32次幂

**Comment by BackerQ** [comment]
堆大于32g使用该参数会怎样呢，为什么不是4g呢正好寻址是2的32次幂

**Comment by bee06** [comment]
> 堆大于32g使用该参数会怎样呢，为什么不是4g呢正好寻址是2的32次幂

-XX:-UseCompressedOops 大于32g 直接关闭即可

**Comment by bee06** [comment]
> > 堆大于32g使用该参数会怎样呢，为什么不是4g呢正好寻址是2的32次幂
> 
> -XX:-UseCompressedOops 大于32g 直接关闭即可

事实证明, 热点 jvm 在堆小于 32 gb 时使用一个技巧来压缩对象指针. 在 java 中, 所有对象都在堆上分配, 并由指针引用。
普通对象指针 (oop) 指向这些对象, 传统上是 cpu 本机字的大小: 32位或 64位, 具体取决于处理器。指针引用值的确切字节位置. 对于32位系统, 这意味着最大堆大小为 4 gb。
对于64位系统, 堆大小可能会变得更大, 但64位指针的开销意味着浪费的空间更多, 原因很简单, 因为指针更大。比浪费的空间更糟糕的是, 当在主内存和各种缓存 (llc、l1 等) 之间移动值时, 较大的指针会消耗更多的带宽。指针引用对象偏移, 而不是指向内存中的确切字节位置。这意味着32位指针可以引用40亿个对象, 而不是40亿个字节。最终, 这意味着堆可以增长到 32 gb 左右的物理大小, 同时仍然使用32位指针. 一旦你越过那个神奇的 ~ 32 gb 边界, 指针就会切换回普通的对象指针。每个指针的大小都会增加, 使用更多的 cpu 内存带宽, 并且实际上会丢失内存。事实上, 在使用压缩的堆拥有同样的有效内存之前, 需要大约 40-50 gb 的分配堆. 这个故事的寓意是: 即使你有多余的内存, 也要尽量避免跨越 32 gb 的堆边界。它会浪费内存, 降低 cpu 性能, 并使 gc 与大堆作斗争
